# Generated by Django 3.1.7 on 2022-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source Address')),
                ('destination_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination Address')),
            ],
        ),
    ]
